### ISSUE TITLE
Great Submission but there is a bug when storing the history

### ISSUE THREAD

**Issue by KapsonLabs** [jaydhales/js-clinic#1]
Hey @jaydhales. There is a critical bug with how your history is stored. First it works fine on initial calculation, The consecutive calculations only show the history as a number. The entire operation should appear as in 8+9

You will see screenshots attached. 

The third screenshot shows a really wierd occurance where the history just appeared at once after i had gone through a series of calculations. Please fix this
<img width="1512" alt="Screenshot 2022-09-14 at 20 24 36" src="https://user-images.githubusercontent.com/20079376/190222982-e90cff88-a287-401b-a52c-c81e4393a1d7.png">
<img width="1512" alt="Screenshot 2022-09-14 at 20 25 26" src="https://user-images.githubusercontent.com/20079376/190223014-8d1e4965-fd63-4752-a49a-aebc1edaf8a9.png">
<img width="1512" alt="Screenshot 2022-09-14 at 20 25 42" src="https://user-images.githubusercontent.com/20079376/190223023-50fe9adb-8534-457e-bd45-2edc178e6bba.png">

**Comment by jaydhales** [comment]
Error has been Fixed
